services:
  ics-hullm-redis:
    ports:
      - 6379:6379

  ics-hullm-worker:
    volumes:
      - ./ics:/app/ics
      - ./lib:/app/lib

  ics-hullm-backend:
    command: uvicorn ics_components.main:app --port 9997 --reload --app-dir src --host 0.0.0.0
    ports:
      - 9898:9898 # python debug server
      - 9997:9997
  ics-hullm-rq-dashboard:
    image: ${REGISTRY_PATH}ics-hullm-worker
    container_name: ics-hullm-rq-dashboard
    build:
      dockerfile: worker.Dockerfile
    command: rq-dashboard --redis-url=redis://ics-hullm-redis:6379
    ports:
      - 9181:9181




