services:
  ics-hullm-redis:
    container_name: ics-hullm-redis
    image: redis:7.4-bookworm
    command:
      - "bash"
      - "-c"
      - "redis-server --maxmemory 1073741824 --maxmemory-policy volatile-lru"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
      - 6379:6379

  ics-hullm-worker:
    build:
      dockerfile: worker.Dockerfile
    volumes:
      - ./ics:/app/ics
      - ./lib:/app/lib
      - ics-hullm-data:/data
    command: rq worker -u redis://ics-hullm-redis:6379 default
    environment:
      REDIS_HOST: ics-hullm-redis
      IS_DATA_DIR: /data
    deploy:
      replicas: 3
    depends_on:
      - ics-hullm-redis

  ics-hullm-backend:
    container_name: ics-hullm-backend
    build:
      dockerfile: backend.Dockerfile
    volumes:
      - ./ics:/app/ics
      - ./lib:/app/lib
      - ics-hullm-data:/data
    command: uvicorn ics_components.main:app --port 9999 --reload --app-dir src --host 0.0.0.0
    environment:
      REDIS_HOST: ics-hullm-redis
      IS_DATA_DIR: /data
    ports:
      - 9999:9999
#      - 9898:9898 # python debug server
    depends_on:
      - ics-hullm-redis

  ics-hullm-rq-dashboard:
    container_name: ics-hullm-rq-dashboard
    build:
      dockerfile: worker.Dockerfile
    command: rq-dashboard --redis-url=redis://ics-hullm-redis:6379
    ports:
      - 9181:9181
#    profiles:
#      - dev

volumes:
  ics-hullm-data:
