services:
  ics-hullm-redis:
    container_name: ics-hullm-redis
    image: redis:7.4-bookworm
    command:
      - "bash"
      - "-c"
      - "redis-server --maxmemory 1073741824 --maxmemory-policy volatile-lru"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  ics-hullm-worker:
    image: ${REGISTRY_PATH}ics-hullm-worker
    build:
      dockerfile: worker.Dockerfile
    volumes:
      - ics-hullm-data:/data
    command: rq worker -u redis://ics-hullm-redis:6379 default
    environment:
      REDIS_HOST: ics-hullm-redis
      IS_DATA_DIR: /data
    deploy:
      replicas: 3
    depends_on:
      ics-hullm-redis:
        condition: service_healthy

  ics-hullm-backend:
    image: ${REGISTRY_PATH}ics-hullm-backend
    container_name: ics-hullm-backend
    build:
      dockerfile: backend.Dockerfile
    volumes:
      - ics-hullm-data:/data
    command: uvicorn ics_components.main:app --port 9997 --app-dir src --host 0.0.0.0
    environment:
      REDIS_HOST: ics-hullm-redis
      IS_DATA_DIR: /data
    ports:
      - "9997:9997"
    depends_on:
      - ics-hullm-redis

volumes:
  ics-hullm-data:
